### PR TITLE
EX1

### PR DESCRIPTION
**Pull request by natiohayun**
Hi Robi
This is my EX1 
netanel Ohayun(Nati)
036507895

### CODE REVIEW

**Comment by robi-y** [comment]
I see only one commit, not the while work history, let's see what went wrong

**Comment by natiohayun** [comment]
Hi Robi
this is the logs file for ex1

nohayun-mac07:hello nohayun$ git hist

```
d64885f 2016-03-17 | Add shread comments to readme (HEAD -> master, shared/master) [Ohayun , Netanel]
b92467b 2016-03-17 | Changed README in orginal repo (shared, origin/greet) [Ohayun , Netanel]
f495c40 2016-03-17 | Updated Rakefile (greet) [Ohayun , Netanel]
8b3d47a 2016-03-17 | Hello uses Greeter [Ohayun , Netanel]
02a7a71 2016-03-17 | Added greeter class [Ohayun , Netanel]
fc574fb 2016-03-17 | Added README [Ohayun , Netanel]
26c8644 2016-03-17 | Added a Rakefile. [natiohayun]
a97662f 2016-03-17 | Moved hello.rb to lib [natiohayun]
6b53945 2016-03-17 | Add an author/email comment [natiohayun]
4a68ccc 2016-03-17 | Added a comment (tag: v1) [natiohayun]
be5b21f 2016-03-17 | Added a default value (tag: v1-beta) [natiohayun]
7a842c5 2016-03-17 | Unrelated change to c [natiohayun]
b647aec 2016-03-17 | Changes for a and b [natiohayun]
a13a31f 2016-03-17 | Added a default value [natiohayun]
89319d3 2016-03-17 | Changes for a and b [natiohayun]
ab20fd5 2016-03-17 | First Commit [natiohayun]
```

**Comment by robi-y** [comment]
:+1:

**Comment by robi-y** [comment]
:100: @natiohayun

**Pull request closed without merging**
