### PR TITLE
Ex4 git immersion lab

### PR DESCRIPTION
**Pull request by ilayze**
Thanks for the git immersion lab!  Really good one!

### CODE REVIEW

**Comment by robi-y** [comment]
Hi,
I don't see the branches and tags, make sure you push them too (as described in the README)

**Comment by ilayze** [comment]
I pushed everything... also I added a screenshot of the tags and branches... hope this is enough.

https://github.com/ilayze/git-immersion/blob/master/gitImmersionBranches.png

**Comment by robi-y** [comment]
[image: Inline image 1]

**Comment by ilayze** [comment]
can't see your previous comment...

**Comment by robi-y** [comment]
I've posted a screenshot from github that showed the the exercise branches
and tags are not uploaded
e.g. https://github.com/ilayze/git-immersion/branches
I expect another branch

**Comment by ilayze** [comment]
Done! you can see the greet branch and also the tags v1-beta and v1.
Let me know if it is ok.

**Comment by robi-y** [comment]
:+1:

**Pull request closed without merging**
